services:
    _defaults:
        public: true
        autoconfigure: true
    
    YottaCms\Bundle\YottaAdminBundle\EventListener\AdminToolbarListener:
        arguments: ['@twig', '@service_container']
        tags: [kernel.event_subscriber]
    
    YottaCms\Bundle\YottaAdminBundle\Controller\DefaultController: ~

    yotta_admin.routing_loader:
        public: false
        class: Symfony\Component\Routing\Router
        arguments: ['@routing.loader', '@@YottaAdminBundle/Resources/config/routing.yml']
        tags: [router]
    
